### PR TITLE
Assorted cleanup

### PR DESCRIPTION
**Pull request by waldyrious**
I decided to re-submit #9 to prevent that work from being lost, but I started doing some cleanup in the meantime, so I decided to submit them first. That way, the doubleTurn PR will be clean.

### CODE REVIEW

**Comment by yakir12** [comment]
This is fantastic, thank you! 
I don't quite understand why the coverage decreased by ~40%...?

**Comment by waldyrious** [comment]
Neither do I :/ the lines [marked as uncovered](https://coveralls.io/builds/14565657/source?filename=src%2FUnitfulAngles.jl) were the ones where I [changed the variable names](https://github.com/yakir12/UnitfulAngles.jl/pull/10/commits/d9984a9e6910f5a69d6456f087e51adcb31ed7e2), but I see no reason why that would make the coverage start failing...

**Comment by yakir12** [comment]
Can you run test with coverage on your branch and see if the relevant lines are getting hit? They really should, if not, something really weird is going on..

**Comment by waldyrious** [comment]
Sure, how do I do that? (Sorry, I haven't been actively developing Julia in a while...)

**Comment by yakir12** [comment]
run:
```julia
Pkg.test("UnitfulAngles", coverage=true)
```
and in the source directory of the package (`joinpath(Pkg.dir("UnitfulAngles"), "src")`) you should fine a file with a `cov` extension (e.g. `UnitfulAngles.jl.9683.cov`). Look in it to see if those lines are being hit.

**Comment by waldyrious** [comment]
Thanks for the detailed instructions :) here's the output: https://gist.github.com/waldyrious/d5ea5dfba5e1e172b4e41b79f483296c

**Comment by yakir12** [comment]
Right. Those lines are getting tested just fine. This was some weird bug with coveralls...

**Comment by waldyrious** [comment]
Thanks. I'll do the #9 re-submission PR next week.

**Pull request merged**
